require 'seed_helper'
SeedHelper::create_tasks_for(:affairs_conditions)
SeedHelper::create_tasks_for(:currencies)
SeedHelper::create_tasks_for(:languages)
SeedHelper::create_tasks_for(:ldap_attributes)
SeedHelper::create_tasks_for(:private_tags)
SeedHelper::create_tasks_for(:product_programs)
SeedHelper::create_tasks_for(:products)
SeedHelper::create_tasks_for(:product_variants)
SeedHelper::create_tasks_for(:public_tags)
SeedHelper::create_tasks_for(:query_presets)
SeedHelper::create_tasks_for(:task_rates)
SeedHelper::create_tasks_for(:task_types)
